project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: packages/app-client

preserve_hierarchy: true

files:
 - source: /src/locales/en.json
   translation: /src/locales/%two_letters_code%.json