packages:
  - 'packages/*'

catalog:
  "@antfu/eslint-config": ^3.6.2
  "@types/node": ^22.5.4
  eslint: ^9.10.0
  tsx: ^4.17.0
  typescript: ^5.6.2
  vitest: ^3.0.9
  "@vitest/coverage-v8": ^3.0.9
  "@corentinth/chisels": ^1.2.1