export const ENCRYPTION_ALGORITHM_AES_256_GCM = 'aes-256-gcm';
export const ENCRYPTION_ALGORITHMS = [ENCRYPTION_ALGORITHM_AES_256_GCM] as const;

export const KEY_DERIVATION_ALGORITHM_PBKDF2_BASE_KEY_SALTED = 'pbkdf2-base-key-salted';
export const KEY_DERIVATION_ALGORITHMS = [KEY_DERIVATION_ALGORITHM_PBKDF2_BASE_KEY_SALTED] as const;

export const COMPRESSION_ALGORITHM_BROTLI = 'brotli';
export const COMPRESSION_ALGORITHM_NONE = 'none';
export const COMPRESSION_ALGORITHMS = [COMPRESSION_ALGORITHM_BROTLI, COMPRESSION_ALGORITHM_NONE] as const;
