name: CI - App Server

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci-app-server:
    name: CI - App Server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/app-server

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i
        working-directory: ./

      - name: Run linters
        run: pnpm lint

      - name: Type check
        run: pnpm typecheck

      - name: Run unit test
        run: pnpm test

      - name: Build the app for Node.js
        run: pnpm build:node

      - name: Build the app for Cloudflare
        run: pnpm build:cloudflare
