name: CI - App Server

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci-app-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/app-server

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          corepack: true
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i
        working-directory: ./

      - name: Run linters
        run: pnpm lint

      - name: Type check
        run: pnpm typecheck

      - name: Run unit test
        run: pnpm test

      - name: Build the app for Node.js
        run: pnpm build:node

      - name: Build the app for Cloudflare
        run: pnpm build:cloudflare
