name: CI - Docs

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci-docs:
    name: CI - Docs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/docs

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i
        working-directory: ./

      - name: Run linters
        run: pnpm lint

      - name: Build the lib
        run: pnpm build
