name: CI - Docs

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci-docs:
    name: CI - Docs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/docs

    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          corepack: true
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i
        working-directory: ./

      - name: Run linters
        run: pnpm lint

      - name: Build the lib
        run: pnpm build
