name: E2E Tests

on:
  deployment_status:

jobs:
  run-e2es:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: packages/app-client

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        corepack: true
        cache: 'pnpm'

    - name: Get Playwright version
      id: playwright-version
      run: echo "PLAYWRIGHT_VERSION=$(jq -r .dependencies.playwright package.json)" >> "$GITHUB_OUTPUT"

    - name: Install dependencies
      run: pnpm i
      working-directory: ./

    - name: Restore Playwright browsers from cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.PLAYWRIGHT_VERSION }}-${{ hashFiles('**/playwright.config.ts') }}
        restore-keys: |
          ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.PLAYWRIGHT_VERSION }}-
          ${{ runner.os }}-playwright-

    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps

    - name: Run e2e tests
      run: pnpm test:e2e
      env:
        BASE_URL: ${{ github.event.deployment_status.environment_url }}
        
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 15
